package com.virtusa.smartwalletguide.backend.util.enums;

public enum Expense_Category {
    BILLS_AND_UTILITIES,ELECTRICITY,GAS,INTERNET,PHONE,RENTERS,WATER,BUSINESS,EDUCATION,ENTERTAINMNET,MOVIES,FAMILY,CHILDREN_AND_BABIES,HOME_IMPOROVENMENT,FEES_AND_CHARGES,FOOD_AND_BEVERAGES,RESTUARANTS,FRIENDS_AND_LOVER,GIFTS_AND_DONATIONS,CHARITY,FUNERAL,MARRIAGE,HEALTH_AND_CARE,SPORTS,INSUARANCES,INVESTMENTS,SHOPPING,ACCESSORIES,CLOTHING,ELECTRONICS,TRANSPORTATION,MAINTAINANCE,PARKING_FEES,PETROL,TAXI,TRAVEL,WIDTHDRAWAL,OTHERS
}
